/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author ME1
 */
public class Loginstudent1 extends javax.swing.JFrame {
    public Integer CNE;

    /**
     * Creates new form login
     */
    public Loginstudent1(Integer CNE) {
        this.CNE = CNE;
        initComponents();
        System.out.println("This : " + CNE);
    }

    public Loginstudent1() {
        initComponents();
        setTitle("Acceuil étudiant");
        txtcin.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtapogee.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtemailstudent.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemailstudent = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtapogee = new javax.swing.JTextField();
        txtcin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtdoc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/loginetudiant.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 380, 340));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/left-arrow.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONNEXION");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, 41));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Remplissez les champs avec vos informations personnelles");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 420, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(199, 226, 255));
        jLabel5.setText("CIN");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 20));

        txtemailstudent.setBackground(new java.awt.Color(25, 118, 211));
        txtemailstudent.setFont(txtemailstudent.getFont().deriveFont(txtemailstudent.getFont().getSize()+2f));
        txtemailstudent.setForeground(new java.awt.Color(255, 255, 255));
        txtemailstudent.setBorder(null);
        txtemailstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailstudentActionPerformed(evt);
            }
        });
        jPanel2.add(txtemailstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("____________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(199, 226, 255));
        jLabel8.setText("Email institutionnelle");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_________________________________________");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(199, 226, 255));
        jLabel10.setText("Numéro apogée");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, -1));

        jLabel11.setBackground(new java.awt.Color(25, 118, 211));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("________________________________");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 170, 30));

        txtapogee.setBackground(new java.awt.Color(25, 118, 211));
        txtapogee.setFont(txtapogee.getFont().deriveFont(txtapogee.getFont().getSize()+2f));
        txtapogee.setForeground(new java.awt.Color(255, 255, 255));
        txtapogee.setBorder(null);
        jPanel2.add(txtapogee, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 140, 30));

        txtcin.setBackground(new java.awt.Color(25, 118, 211));
        txtcin.setFont(txtcin.getFont().deriveFont(txtcin.getFont().getSize()+2f));
        txtcin.setForeground(new java.awt.Color(255, 255, 255));
        txtcin.setBorder(null);
        jPanel2.add(txtcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("__");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 40, 20));

        jLabel7.setForeground(new java.awt.Color(199, 226, 255));
        jLabel7.setText("Document");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 220, 80, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attestation de scolarité", "Relevé de notes", "Attestation de réussite", "Convention de stage" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 240, 30));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Le document choisit :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 280, 130, -1));

        txtdoc.setBackground(new java.awt.Color(25, 118, 211));
        txtdoc.setForeground(new java.awt.Color(255, 255, 255));
        txtdoc.setBorder(null);
        txtdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocActionPerformed(evt);
            }
        });
        jPanel2.add(txtdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 250, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(25, 118, 211));
        jButton1.setText("Réclamer");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 100, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(25, 118, 211));
        jButton2.setText("Continuer");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));

        setSize(new java.awt.Dimension(917, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }// GEN-LAST:event_jLabel2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }// GEN-LAST:event_formWindowOpened

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel12MouseClicked
        first firstScreen = new first();

        // Set the reference to the current instance (Loginstudent1)
        firstScreen.setLoginStudentInstance(this);

        // Show the first screen
        firstScreen.setVisible(true);

        // Close the current instance (Loginstudent1)
        this.dispose();
    }// GEN-LAST:event_jLabel12MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // check if the fields are empty
        if (txtcin.getText().equals("") || txtapogee.getText().equals("") || txtemailstudent.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        } else {
            // setup connection
            String Surl, Suser, Spass;
            Surl = "jdbc:mysql://localhost:3306/gl";
            Suser = "root";
            Spass = "";
            String query;
            try {
                // check if the student exists and the infos are correct
                Connection con = DriverManager.getConnection(Surl, Suser, Spass);
                Statement st = con.createStatement();
                query = "SELECT * FROM `student` WHERE `CIN` = '" + txtcin.getText() + "' AND `CNE` = '"
                        + txtapogee.getText() + "' AND `email` = '" + txtemailstudent.getText() + "'";
                ResultSet res = st.executeQuery(query);
                if (res.next()) {
                    // get the id of the student
                    this.CNE = res.getInt("CNE");
                    // go the reclamations page
                    this.setVisible(false);
                    new Reclamation(CNE, txtdoc.getText()).setVisible(true);
                    // set position to default
                    this.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Veuillez vérifier vos informations");
                }
            } catch (Exception e) {
                System.out.println("Error db " + e.getMessage());
            }
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }// GEN-LAST:event_jLabel14MouseClicked

    private void txtemailstudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtemailstudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtemailstudentActionPerformed

    private void txtdocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtdocActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtdocActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedValue = jComboBox1.getSelectedItem().toString();

        // set this selected value into textfiled
        txtdoc.setText(selectedValue);
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // check if the fields are empty
        if (txtcin.getText().equals("") || txtapogee.getText().equals("") || txtemailstudent.getText().equals("")
                || txtdoc.getText().equals("")) {
            showMessageDialog(null, "Veuillez remplir tous les champs");
        } else {
            // setup connection
            String Surl, Suser, Spass;
            Surl = "jdbc:mysql://localhost:3306/gl";
            Suser = "root";
            Spass = "";
            String query;
            Integer id = Integer.parseInt(txtapogee.getText());
            try {
                Connection con = DriverManager.getConnection(Surl, Suser, Spass);
                Statement st = con.createStatement();
                // check if the student exists
                query = "SELECT * FROM `student` WHERE `CIN` = '" + txtcin.getText() + "' AND `CNE` = '"
                        + txtapogee.getText() + "' AND `email` = '" + txtemailstudent.getText() + "'";
                ResultSet res = st.executeQuery(query);

                if (res.next()) {
                    // get the id of the student
                    this.CNE = res.getInt("CNE");
                    // switch case to check the document type
                    switch (txtdoc.getText()) {
                        case "Attestation de scolarité":
                            // check if a demand is already sent (same id and traté is 0)
                            query = "SELECT * FROM `demande_as` WHERE `user_id` = '" + id + "' AND `traite` = '0'";
                            res = st.executeQuery(query);
                            if (res.next()) {
                                showMessageDialog(null, "Vous avez déjà envoyé une demande, veuillez attendre");
                            } else {
                                query = "INSERT INTO demande_as(user_id) VALUES ('" + id + "')";
                            st.executeUpdate(query);
                            JOptionPane.showMessageDialog(null, "Votre demande a été envoyée avec succès");
                            }
                            
                            break;
                        case "Relevé de notes":
                            this.setVisible(false);
                            new releve_note(CNE).setVisible(true);
                            // set position to default
                            this.setLocationRelativeTo(null);
                            break;
                        case "Attestation de réussite":
                            this.setVisible(false);
                            new Attestation_reuss(CNE).setVisible(true);
                            // set position to default
                            this.setLocationRelativeTo(null);
                            break;
                        case "Convention de stage":
                            this.setVisible(false);
                            new stageDoc(CNE).setVisible(true);
                            // set position to default
                            this.setLocationRelativeTo(null);
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Veuillez choisir un document");
                    }
                } else {
                    showMessageDialog(null, "Veuillez vérifier vos informations");
                }
                con.close();
            } catch (Exception e) {
                System.out.println("Error db " + e.getMessage());
            }
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginstudent1.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginstudent1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtapogee;
    private javax.swing.JTextField txtcin;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtemailstudent;
    // End of variables declaration//GEN-END:variables
}
